"""init db

Revision ID: 043bd5d5b454
Revises: 
Create Date: 2025-01-13 17:38:10.729802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043bd5d5b454'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=75),
               existing_nullable=False)
    op.create_unique_constraint('unique_book', 'books', ['title', 'author'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_book', 'books', type_='unique')
    op.alter_column('books', 'title',
               existing_type=sa.String(length=75),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
